from enum import Enum, unique

@unique
class StreetNames(Enum):
    GO = 0
    MEDITERANIAN_AVENUE = 1
    COMMUNITY_CHEST_0 = 2
    BALTIC_AVENUE = 3
    INCOME_TAX = 4
    READING_RAILROAD = 5
    ORIENTAL_AVENUE = 6
    CHANCE_0 = 7
    VERMONT_AVENUE = 8
    CONNECTICUT_AVENUE = 9
    JAIL = 10
    ST_CHARLES_PLACE = 11
    ELECTRIC_COMPANY = 12
    STATES_AVENUE = 13
    VIRGINIA_AVENUE = 14
    PENNSYLVANIA_RAILROAD = 15
    ST_JAMES_PLACE = 16
    COMMUNITY_CHEST_1 = 17
    TENNESSEE_AVENUE = 18
    NEW_YORK_AVENUE = 19
    FREE_PARKING = 20
    KENTUKY_AVENUE = 21
    CHANCE_1 = 22
    INDIANA_AVENUE = 23
    ILLINOIS_AVENUE = 24
    BO_RAILROAD = 25
    ATLANTIC_AVENUE = 26
    VENTNOR_AVENUE = 27
    WATER_WORKS = 28
    MARVIN_GARDENS = 29
    GO_TO_JAIL = 30
    PACIFIC_AVENUE = 31
    NORTH_CAROLINA_AVENUE = 32
    COMMUNITY_CHEST_2 = 33
    PENNSYLVANIA_AVENUE = 34
    SHORT_LINE_RAILROAD = 35
    CHANCE_2 = 36
    PARK_PLACE = 37
    LUXURY_TAX = 38
    BOARDWALK = 39